### ISSUE TITLE
Ambiguity in main.py

### ISSUE THREAD

**Issue by shashwat623** [nullbyte91/openvino-people_counter_IoT_app#2]
Hey @nullbyte91 
Very well formatted and good approach to the udacity project code, helped me a lot. Thanks!!
However, I believe your code only implements a scenario where only one person is present in the frame at a time and fails to count multiple people( be it for entering or leaving the frame and its corresponding counter update), which is required in the specifications.
How can this be implemented? Maybe you can correct me.

**Comment by nullbyte91** [comment]
@shashwat623 Yes You're right. The current implementation based on fixed ROI. We have to use tracking techniques i.e dlib or Kalman filter. I tried Kalman with the detection output of OpenVino, and the tracking was poor. However, the same implementation was working well with tensorflow and Caffe detection output. I have a plan to integrate the tracking technique. 

You can find the Kalman filter implementation here. https://github.com/nullbyte91/human-detection-and-tracking

**Comment by shashwat623** [comment]
Alright @nullbyte91, thanks for letting me know. Cheers!!
